---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crt
subjects:
- kind: ServiceAccount
  name: default
  namespace: system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crt
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
